### ISSUE TITLE
Routes with regular expressions in them don't use the variable as a function parameter

### ISSUE THREAD

**Issue by Jleagle** [cubex/framework#9]
public function getRoutes()
	{
		return [
			'page/(.*)' => 'page',
		];
	}

	public function page($var)
	{
		// $var is undefined
	}

**Comment by TomK** [comment]
Only named route segments are passed to the functions.  You can get the full route as an argument using the @all parameter notation as follows:

```
public function getRoutes()
{
    return [
        'page/:path@all' => 'page',
    ];
}

public function page($var)
{
    // request:   /page/full/path/here
    // $var === '/full/path/here'
}
```
